version: "3.8"

services:
  server:
    build:
      context: .
      # dockerfile: src/server/Dockerfile
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/crypto-payments
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - ETHEREUM_MNEMONIC=${ETHEREUM_MNEMONIC}
      - CHAIN_ID=${CHAIN_ID}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
